### ISSUE TITLE
Doesn't lock

### ISSUE THREAD

**Issue by Skillmon** [benruijl/sflock#26]
I reinstalled `sflock` today, building it from sources in Arch through the AUR package. `sflock` doesn't lock, it starts, but accepts any string as the correct password.

**Comment by Esvecha** [comment]
I have this same issue. I've noticed that I can't change tty's after running sflock. Using chvt won't change tty's either.

Something sflock is running to block the tty's is hanging perhaps?

I've only noticed this on 1/2 two machines that I have sflock on. Still works perfectly on the other.

**Comment by qwelyt** [comment]
@benruijl Will this be fixed by you or have you deprecated the project?

**Comment by Skillmon** [comment]
Just realized this might be (or most likely is) a duplicate of https://github.com/benruijl/sflock/issues/24

**Comment by benruijl** [comment]
@qwelyt Sadly I've never managed to reproduce the bug, which makes it hard to find out what's going on. I can see what `sxlock` does differently.

Regarding deprecation, the project is not deprecated but I am sadly very short on time these days. If someone wants to study this problem, I'm glad to merge a pull request!
